AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 4Developers SAM

Globals:
    Function:
        Timeout: 3


Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: hello_world/
            Handler: app.lambda_handler
            Runtime: python3.7
            Events:
                GetEvent:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: get
                PostEvent:
                    Type: Api
                    Properties:
                        Path: /
                        Method: post
            Policies: AmazonDynamoDBFullAccess
            Environment:
                Variables:
                    table_name: !Ref DynamoTable
            Layers: 
            - arn:aws:lambda:eu-central-1:655379451354:layer:xray:1
            Tracing: Active

    DynamoTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            ProvisionedThroughput:
                WriteCapacityUnits: 1
                ReadCapacityUnits: 1
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
                - AttributeName: name
                  AttributeType: S
            KeySchema:
                - KeyType: HASH
                  AttributeName: id
                - KeyType: RANGE
                  AttributeName: name

Outputs:

    APIEndpoint:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"


